using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;  //Lua

namespace Content.Client.UserInterface.Systems.MenuBar.Widgets
{
    [GenerateTypedNameReferences]
    public sealed partial class GameTopMenuBar : UIWidget
    {
        public GameTopMenuBar()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
