- type: entity
  id: MonoAISTCShuttleSpawnerScheduler
  parent: BaseGameRule
  components:
    - type: BasicStationEventScheduler
      scheduledGameRules: !type:NestedSelector
        tableId: MonoAISTCEventsTable
      minimumTimeUntilFirstEvent: 1800 # 30 minutes
      minMaxEventTiming:
        min: 5400 # 90 minutes between events
        max: 13500 # 225 minutes between events

- type: entityTable
  id: MonoAISTCEventsTable
  table: !type:AllSelector # we need to pass a list of rules, since rules have further restrictions to consider via StationEventComp
    children:
      - id: UnknownShuttleZenith
      #- id: UnknownShuttleRazor
      - id: UnknownShuttleNebula
      - id: UnknownShuttlePerunAI
      - id: UnknownShuttlePozvizdAI
      - id: UnknownShuttleStribogAI

- type: entity
  abstract: true
  parent: BaseGameRule
  id: BaseRandomShuttleRule
  components:
  - type: StationEvent
    weight: 10
    reoccurrenceDelay: 90
    duration: 1
    maxOccurrences: 24 # should be the same as [copies] in /ship_spawns.yml Lua
  - type: RuleGrids
  - type: LoadMapRule
