# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: entity
  id: MedipenTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: медипен техфаб (машинная плата)
  description: Машинная плата техфаба медипенов
  components:
    - type: Sprite
      state: medical
    - type: MachineBoard
      prototype: MedipenTechfab
      requirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker
    - type: StealTarget
      stealGroup: MedipenTechFabCircuitboard

- type: entity
  id: ThrusterLuaMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: thruster luatech machine board
  categories: [HideSpawnMenu]
  suffix: Lua
  components:
  - type: Sprite
    sprite: _Lua/Objects/Misc/module.rsi
    state: ltthruster
  - type: MachineBoard
    prototype: ThrusterLua
    stackRequirements:
      Plasteel: 5
      PurCapacitor: 4

- type: entity
  id: ThrusterLuaBuildMachineCircuitboard
  parent: [ThrusterLuaMachineCircuitboard, BaseMachineCircuitboard]
  name: thruster luatech machine board
  suffix: Lua
  components:
  - type: MachineBoard
    prototype: ThrusterLuaBuild
    requirements:
      Capacitor: 4
    stackRequirements:
      Plasteel: 5

- type: entity
  id: MachineShieldPLTCircuitboard
  parent: BaseMachineCircuitboard
  name: PLT shield generator board
  description: A machine board for a shield generator.
  categories: [HideSpawnMenu]
  suffix: Lua
  components:
  - type: Sprite
    sprite: _Lua/Objects/Misc/module.rsi
    state: ltshieldgen
  - type: MachineBoard
    prototype: CircularShieldLua
    componentRequirements:
      AmeFuelContainer:
        amount: 2
        defaultPrototype: AmeJar
    stackRequirements:
      Glass: 10
      Uranium: 10
      Plasma: 30
      Plasteel: 10
      PurCapacitor: 4
      PurMatterBin: 2

- type: entity
  id: MachineShieldPLTCircuitboardBuild
  parent: [MachineShieldPLTCircuitboard, BaseMachineCircuitboard]
  suffix: Lua
  components:
  - type: MachineBoard
    prototype: CircularShieldLuaBuild
    componentRequirements:
      AmeFuelContainer:
        amount: 2
        defaultPrototype: AmeJar
    requirements:
      Capacitor: 4
      MatterBin: 2
    stackRequirements:
      Glass: 10
      Uranium: 10
      Plasma: 30
      Plasteel: 10
