/*
 * LuaWorld - This file is licensed under AGPLv3
 * Copyright (c) 2025 LuaWorld Contributors
 * See AGPLv3.txt for details.
 */
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._NF.Bank.BUI;
using Content.Shared._Lua.Bank.Events;
using Robust.Client.UserInterface;
using Robust.Client.Graphics;
using Robust.Client.Utility;
using Content.Shared.CartridgeLoader;

namespace Content.Client._Lua.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class YupiTransferUiFragment : BoxContainer
{
    // Feature: PDA cartridge for person-to-person money transfers and loan repayments.
    // Why: Provides quick access to YUPI operations without visiting consoles.
    // UX: static captions localized via Loc; copy button shows current code and copies it to clipboard.
    private BoundUserInterface _ui = default!;
    private LineEdit _codeInput = default!;
    private LineEdit _amountInput = default!;
    private Label _ownCode = default!; // no longer shown; keep for state
    private Label _balance = default!;
    private Button _sendButton = default!;
    private Button _repayButton = default!;
    private Button _copyCodeButton = default!;
    private Label _lblOwnCodeTitle = default!;
    private Label _lblBalanceTitle = default!;
    private Label _lblTargetCodeTitle = default!;
    private Label _lblAmountTitle = default!;
    private Label _lblDueTitle = default!;
    private Label _due = default!;

    public YupiTransferUiFragment()
    {
        RobustXamlLoader.Load(this);
        _codeInput = FindControl<LineEdit>("CodeInput");
        _amountInput = FindControl<LineEdit>("AmountInput");
        // _ownCode removed from XAML; use button text instead
        _balance = FindControl<Label>("Balance");
        _sendButton = FindControl<Button>("SendButton");
        _repayButton = FindControl<Button>("RepayButton");
        _lblDueTitle = FindControl<Label>("LblDueTitle");
        _due = FindControl<Label>("Due");
        _copyCodeButton = FindControl<Button>("CopyCodeButton");
        _lblOwnCodeTitle = FindControl<Label>("LblOwnCodeTitle");
        _lblBalanceTitle = FindControl<Label>("LblBalanceTitle");
        _lblTargetCodeTitle = FindControl<Label>("LblTargetCodeTitle");
        _lblAmountTitle = FindControl<Label>("LblAmountTitle");
        _sendButton.OnPressed += _ =>
        {
            if (_ui == null)
                return;
            if (int.TryParse(_amountInput.Text, out var amt))
            {
                var msg = new YupiTransferRequestMessage
                {
                    TargetCode = _codeInput.Text.Trim(),
                    Amount = amt
                };
                _ui.SendMessage(new CartridgeUiMessage(msg));
            }
        };

        _repayButton.OnPressed += _ =>
        {
            if (_ui == null)
                return;
            if (int.TryParse(_amountInput.Text, out var amt))
            {
                var msg = new YupiRepayLoanRequestMessage
                {
                    TargetCode = _codeInput.Text.Trim(),
                    Amount = amt
                };
                _ui.SendMessage(new CartridgeUiMessage(msg));
            }
        };

        _copyCodeButton.OnPressed += _ =>
        {
            var text = _copyCodeButton.Text;
            if (!string.IsNullOrEmpty(text))
                IoCManager.Resolve<IClipboardManager>().SetText(text);
        };
    }

    public void Initialize(BoundUserInterface ui)
    {
        _ui = ui;
    }

    public void UpdateState(YupiTransferUiState state)
    {
        _copyCodeButton.Text = string.IsNullOrWhiteSpace(state.OwnCode) ? "------" : state.OwnCode.ToUpperInvariant();
        _balance.Text = state.Balance.ToString();

        // Localize static labels via Loc
        _lblOwnCodeTitle.Text = Loc.GetString("yupi-ui-own-code");
        _lblBalanceTitle.Text = Loc.GetString("yupi-ui-balance");
        _lblTargetCodeTitle.Text = Loc.GetString("yupi-ui-target-code");
        _lblAmountTitle.Text = Loc.GetString("yupi-ui-amount");
        _sendButton.Text = Loc.GetString("yupi-ui-send");
        _repayButton.Text = Loc.GetString("yupi-ui-repay");
        _lblDueTitle.Text = Loc.GetString("yupi-ui-outstanding");
        _due.Text = state.Outstanding.ToString();
    }
}


