- type: job
  id: CentralCommandCargo
  name: job-name-centcomcargo
  description: job-description-centcomcargo
  playTimeTracker: JobCentralCommandCargo
  salary: 100000
  setPreference: true
  startingGear: CCCargo
  icon: JobIconCCCargoTech
  supervisors: job-supervisors-hoh
  canBeAntag: false
  weight: 1
  requireAdminNotify: true
  joinNotifyCrew: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 126000
    - !type:RoleTimeRequirement
      role: JobCentralCommandAssistant
      time: 21600
    - !type:DepartmentTimeRequirement
      department: CentCom
      time: 43200
  whitelisted: true
  access:
    - CentralCommand
    - CCCargo
    - Cargo
    - Maintenance
    - Salvage
    - External
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - CentralCommand
        - type: AntagImmune
        - type: Company
          companyName: CentComm

- type: jobIcon
  parent: JobIcon
  id: JobIconCCCargoTech
  icon:
    sprite: /Textures/Backmen/Icons/jobicon.rsi
    state: CargoTechnician


- type: entity
  parent: OrdenPDA
  id: CCCargoPDA
  name: Centcom Cargo PDA
  description: Light green sign of walking bureaucracy.
  components:
    - type: Appearance
      appearanceDataInit:
        enum.PdaVisuals.PdaType:
          !type:String
          pda-centcomcargo
    - type: Pda
      id: IDCardCentComCargoBackmen
      penSlot:
        startingItem: PenCentcom
        whitelist:
          tags:
            - Write
    - type: PdaBorderColor
      borderColor: "#00842e"
    - type: Icon
      sprite: /Backmen/Objects/Devices/pda.rsi
      state: pda-centcomcargo

- type: entity
  parent: CentcomIDCardDeathsquad
  id: IDCardCentComCargoBackmen
  name: ID карта ЦК Грузчика
  components:
    - type: Sprite
      sprite: /Backmen/Objects/Misc/id_cards.rsi
      layers:
        - state: card_centcom # Backmen
        - state: sub_department # Backmen
          color: "#b18644"
        - state: frame_default # Backmen
          color: "#b18644"
        - state: idcargotechnician
    - type: PresetIdCard
      job: CentralCommandCargo
    - type: Access
      tags:
        - CCCargo
        - CentralCommand
        - Cargo
        - Maintenance
        - Salvage
